### ISSUE TITLE
Identify the version of HTTP Signature used

### ISSUE THREAD

**Issue by evanp** [swicg/activitypub-http-signature#1]
This is important for anyone who wants to integrate with the fediverse.

**Comment by nightpool** [comment]
Also, a Upgrading Considerations section for the work necessary to upgrade between different versions of the algorithms would be very helpful to implementers trying to understand the potential versions they may see in practice

**Comment by snarfed** [comment]
#17 may subsume this, since there's no one single version used, there's just the spread of which existing projects use which versions.

**Comment by snarfed** [comment]
Related: looks like the HTTP Sig RFC hit the Published Standard stage! https://datatracker.ietf.org/doc/html/rfc9421

**Comment by snarfed** [comment]
News since this issue was filed: the spec finally got published as an RFC! https://datatracker.ietf.org/doc/html/rfc9421

**Comment by snarfed** [comment]
From https://github.com/swicg/activitypub-http-signature/issues/17#issuecomment-2002202313 :

> Based on this data and other projects anecdotally, [cavage-12](https://datatracker.ietf.org/doc/html/draft-cavage-http-signatures) is still the most commonly supported version in the fediverse. [Mastodon is a big contributing factor here.](https://docs.joinmastodon.org/spec/security/#http)
