### ISSUE TITLE
Describe potential improvements

### ISSUE THREAD

**Issue by evanp** [swicg/activitypub-http-signature#10]
I can think of at least two:

1. Using the most recent version of HTTP BIS (although I don't think there's a final version yet!)
2. Using the most recent version of W3C Security (2?)

**Comment by evanp** [comment]
One principle that might need to be articulated is that double-knocking might be necessary.

So if you make a request with AP+Sig 2.0, and it fails, fall back to AP+Sig 1.0, and try again. If it works, maybe set a flag that the remote server doesn't support 2.0 yet (so you cut down on retries). You might need to try 2.0 again randomly until the remote server upgrades, which honestly may take years.

It's not great, but it maximizes compatibility.

**Comment by perillamint** [comment]
Worth to note that Mastodon does not like non-string [RFC 8941](https://www.rfc-editor.org/rfc/rfc8941) formatted headers, which prevents stuffing `httpbis` and `cavage` in the same request.

I agree that double-knocking is current best approach.

**Comment by snarfed** [comment]
Initial double-knocking text is in https://github.com/swicg/activitypub-http-signature/issues/29#issuecomment-2005080039
