### ISSUE TITLE
Deadlock issues

### ISSUE THREAD

**Issue by evanp** [swicg/activitypub-http-signature#11]
If I have to use HTTP Signature to fetch the key defined in the key ID, there's a regression issue.

The key resource, actor resource, and/or server actor resources have to be available with unsigned GET requests.

**Comment by nightpool** [comment]
I'm not aware of any implementation in practice that has the "deadlock" issue, even Authorized Fetch Mastodon makes the actor's key resource available with an unsigned GET request.

**Comment by nightpool** [comment]
I learned recently that this was a change made between the original release of Authorized Fetch (which I reviewed) and a subsequent release which locked user actors down further. This change was made for compatibility reasons (so that instances not supporting authorized fetch didn't show incomplete profiles)

**Comment by evanp** [comment]
If I remember correctly, Threads actors require signed requests, which caused a deadlock unless the requestor allowed unsigned requests for keys.

**Comment by snarfed** [comment]
Huh, I could have sworn they stopped requiring sigs, and said it was a bug that the originally did require them, but I checked just now and they still are required.

Regardless, the instance actor solution works against servers like Threads too, even if they don't have their own instance actor.

**Comment by evanp** [comment]
@snarfed yes, they fixed it. It doesn't mean we shouldn't tell the next implementer to avoid that same bug!

**Comment by snarfed** [comment]
First pass at text here is in https://github.com/swicg/activitypub-http-signature/issues/12#issuecomment-1965494431
