### ISSUE TITLE
Describe authorized fetch and the server actor

### ISSUE THREAD

**Issue by evanp** [swicg/activitypub-http-signature#12]
Describe the authorized fetch mode and how to identify a request without an actor using a server actor.

**Comment by nightpool** [comment]
I'm not 100% convinced Server Actors are a good idea for most use-cases, I would think that use-cases involving "server" actors would be better supported by having individual Applications or Service actors that do individual tasks on your server rather than having a monolithic "server actor". But i'm open to other opinions.

**Comment by snarfed** [comment]
The easy first pass at text here is just to copy https://www.w3.org/wiki/SocialCG/ActivityPub/Authentication_Authorization#Authorized_fetch more or less verbatim. Thoughts?

> ## Authorized fetch
> 
> Some servers have a feature called authorized fetch, aka secure mode, which requires all HTTP GET requests for ActivityPub objects to include HTTP Signatures. This is intended to increase the server's control over who can access its data. [From Mastodon's documentation](https://docs.joinmastodon.org/admin/config/#authorized_fetch):
> 
> As a result, through the authentication mechanism and avoiding re-distribution mechanisms that do not have your server in the loop, it becomes possible to enforce who can and cannot retrieve even public content from your server, e.g. servers whose domains you have blocked.
> 
> Servers with authorized fetch enabled generally don't enforce any fine grained access control over the actors whose signatures they require to fetch data. They usually only reject requests from actors on domains that they've blocked at the server level. (This means that the name authorized fetch is maybe partially a misnomer, and something like signed fetch might be more appropriate.)
> 
> ## Instance actors
> 
> One consequence of [authorized fetch](https://www.w3.org/wiki/SocialCG/ActivityPub/Authentication_Authorization#authorized_fetch) is that signed fetches can end up in a kind of deadlock or infinite loop. If server a.example fetches https://b.example/bob with https://a.example/alice's signature, and b.example doesn't have alice's public key, it will get it by fetching https://a.example/alice with https://b.example/bob's signature. a.example won't have bob's public key either, so it will again try to fetch https://b.example/bob, and the cycle will continue.
> 
> To prevent this, servers with authorized fetch enabled often use an [instance actor](https://seb.jambor.dev/posts/understanding-activitypub-part-4-threads/#the-instance-actor) to sign object fetches. This is generally a "server-level" actor, separate from any normal user, that doesn't require an HTTP Signature to be fetched. This breaks the loop of fetching each actor back and forth to validate their signatures.
