### ISSUE TITLE
Non-goal: client side signatures

### ISSUE THREAD

**Issue by snarfed** [swicg/activitypub-http-signature#20]
There's a lot of promising history and work on generating signatures client side, so that users can keep more control over their keys and how/whether they let servers or other parties use them custodially. This is worth digging into! It's a big topic though, regrettably probably too big for this specific report. Could be worth a follow-up or its own report though!

Background: https://lists.w3.org/Archives/Public/public-swicg/2024Feb/0013.html

**Comment by evanp** [comment]
The use case is as follows:

client software C1 uses an actor account A1 on server S1 with client API authentication method like OAuth 2.0.

C1 wants to load object O2 on server S2 with actor A1's authorization. The OAuth 2.0 bearer token used for accessing objects on server S1 won't work. Server S2 has no way to resolve that token.*

One solution for this is client-side HTTP signature keys.

A better solution (IMHO) is the [proxyUrl](https://www.w3.org/TR/activitypub/#actor-objects) endpoint. C1 calls the proxyUrl using an OAuth 2.0 bearer token with the ID of the resource it wants, and server S1 uses HTTP Signature to request it from server S2 with actor A1's authorization.

* Well... usually. This might be a nice use-case for JWTs. Hmm.
