### ISSUE TITLE
Interactions with HTTP caching

### ISSUE THREAD

**Issue by evanp** [swicg/activitypub-http-signature#23]
I think the `Signature` header really messes things up for HTTP caching using `Last-Modified` and `ETag` headers.

Because the authentication is all in the `Signature` header, you need to include the `Signature` in the `Vary` header. But the signature will never be the same twice -- it will always include the `Date`,  so the signature field will always be different.

It might be possible to leave the signature out of the `Vary` field for public objects, unless you're using authorized fetch.

Somebody correct me if I'm way off here!

**Comment by snarfed** [comment]
Hmm. Are you worried about 200 responses to signed requests getting cached and returned to later requests without signatures?

Otherwise, HTTP error responses like 401s to unsigned requests generally aren't cached, right?

**Comment by nightpool** [comment]
this is correct, using authorized fetch basically means you can never use
HTTP caching

Of course, your welcome to do your caching "inside" of the HTTP Signature
validation, with your application cache, as long as you're sure you've done
all your authorization checks first.

**Comment by evanp** [comment]
> Hmm. Are you worried about 200 responses to signed requests getting cached and returned to later requests without signatures?
> 
> Otherwise, HTTP error responses like 401s to unsigned requests generally aren't cached, right?

I'm talking about If-Modified-Since, If-None-Match, 304 Not Modified style caching.

**Comment by snarfed** [comment]
I got curious about this just now and spot tested some of the most popular fediverse server projects by fetching objects with HTTP Signatures. _None_ of them currently include `Signature` in `Vary`. Here's what I got:

* Pleroma: Accept-Encoding
* Mastodon: Accept-Encoding, Accept, Accept-Language, Cookie, Signature, Origin
* Friendica: Accept-Encoding
* Pixelfed: Accept-Encoding
* Lemmy: Accept-Encoding
* PeerTube: Accept-Encoding, Accept-Language

Hell, forget `Signature`, only Mastodon even includes `Accept`! Ugh.

**Comment by snarfed** [comment]
Initial draft text below. Please review and revise!

---

HTTP responsees are cached in a wide variety of ways across the web. HTTP Signatures in ActivityPub requests can affect the resulting responses, so clients and servers both need to take signatures account when interacting with caches.

The main thing ActivityPub servers need to do is include `Signature` in their `Vary` header for responses that depend on request signatures, eg if they require [authorized fetch](TODO) and would return a 4xx error if a signature is missing or invalid. This prevents valid responses from being cached and returned to other requests in the future with missing or invalid signatures.

(This is similar to including `Content-Type` in the `Vary` response header for URLs that can return either user-facing HTML or ActivityStreams JSON, depending on content negotiation.)

One downside of this is that ActivityPub objects from servers that require authorized fetch generally can't be cached. HTTP Signatures include timestamps and are generated by different private keys, so they'll almost never be the same across requests. This is an unfortunate side effect, but necessary for servers that want to control access based on the requester's identity.

**Comment by evanp** [comment]
@snarfed awesome, thank you!
