### ISSUE TITLE
List of HTTP Signature Implementations

### ISSUE THREAD

**Issue by AaronNGray** [swicg/activitypub-http-signature#31]
# List of HTTP Signature Implementations by language and platform

 - JavaScript
    - Node.js
        - https://github.com/dariusk/express-activitypub/blob/master/routes/api.js#L23
 
 - TypeScript
    - Node.js
       - https://gitlab.com/paulkiddle/activitypub-http-signatures/-/blob/main/src/main.ts?ref_type=heads

**Comment by snarfed** [comment]
Here's the official list: https://github.com/w3c-ccg/http-signatures/issues/1 . It's big!
