### ISSUE TITLE
Identify the required headers

### ISSUE THREAD

**Issue by evanp** [swicg/activitypub-http-signature#4]
I think right now they are:

- Host
- Date
- Digest (if there is a request body)

Others would be helpful.

**Comment by perillamint** [comment]
Worth to note that `Date` can be substituted with `created` parameter in cavage/httpbis signature. (In feature-wise. It should be noted that compatibility can be an issue in here)

Also, the list should include `Content-Type` (if there is a request body) to prevent confusing between content-types.

**Comment by nightpool** [comment]
Mastodon uses the Date header for older signatures and the (created)
pseudo-header for hs2019 signatures
https://github.com/mastodon/mastodon/blob/main/app/controllers/concerns/signature_verification.rb

**Comment by perillamint** [comment]
> > Worth to note that `Date` can be substituted with `created` parameter in cavage/httpbis signature. (In feature-wise. It should be noted that compatibility can be an issue in here)
> 
> Is this supported by any Fediverse software?
> 
> > Also, the list should include `Content-Type` (if there is a request body) to prevent confusing between content-types.
> 
> Is this required by any Fediverse software?

Ah, sorry. I confused it with other header (actually, pseudo-header) requirement: `(request-target)`.

Inspected Mastodon and Misskey code, and found out they both signs:

- `(request-target)`
- `Host`
- `Date`
- `Digest`

And Mastodon requires all four headers intact but Misskey only requires

- `Host`
- `Digest`

(Note: Misskey before 2023.11.1-beta.1 does not mandate any header. It just wants the request signed.)

**Comment by edent** [comment]
Mastodon sends `headers="(request-target) host date digest content-type"`

**Comment by omz13** [comment]
If going strictly by the book, "Digest" is obsoleted by "Content-Digest". See my comment on #28.

**Comment by snarfed** [comment]
> > Also, the list should include `Content-Type` (if there is a request body) to prevent confusing between content-types.
> 
> Is this required by any Fediverse software?

I'm curious about this too. Afaik the only AP S2S requests with bodies are [inbox delivery POSTs](file:///Users/ryan/docs/activitypub_20180123.html#delivery), and [those requests' content types are always either `application/ld+json; profile="https://www.w3.org/ns/activitystreams"` or `application/activity+json`](file:///Users/ryan/docs/activitypub_20180123.html#server-to-server-interactions), which are interchangeable. Requests with other content types are errors and should result in 405 responses.

Including `Content-Type` in the signed headers is obviously fine, and harmless! I just don't know that it's necessary in practice.

**Comment by snarfed** [comment]
Incorporating into #33.

**Comment by snarfed** [comment]
Good points, thank you! Incorporated into #33.
