### ISSUE TITLE
Key rotation?

### ISSUE THREAD

**Issue by jernst** [swicg/activitypub-http-signature#40]
Is there anything that can be said in the report about key rotations? Like what common implementations do (both on the generation and the signature verification side) or what a best practice should be?

**Comment by snarfed** [comment]
Sure! I don't know how in scope key rotation is, and afaik it's (sadly) not yet common in general in the fediverse, and opinions and experience [vary](https://socialhub.activitypub.rocks/t/key-rotation-notification/562)[ widely](https://socialhub.activitypub.rocks/t/newbie-lifecycle-of-keys/3791), so I'm reluctant to say too much, but I can definitely mention it.

**Comment by jernst** [comment]
Would it be useful to add a section that lists open issues?

**Comment by snarfed** [comment]
Hmm! I'm not sure? There's the non-goals section, but otherwise, I don't really intend the report to describe a project or track ongoing/new work, it's more a description of the current state.

**Comment by jernst** [comment]
For me, open issues are always part of the current state ("known bugs") but YMMV for sure.

**Comment by evanp** [comment]
I think Mastodon will re-fetch a key if verification with the cached key fails. Pseudocode like this:

```
key = get_cached_key(keyId)

if (key) {
    if (verify_signature(signature, key)) {
        return true;
    }
}

key = get_remote_key(keyId)

if (verify_signature(signature, key)) {
    return true;
} else {
    return false;
}
```

**Comment by evanp** [comment]
Anyway, that's how to deal with key rotation.

**Comment by snarfed** [comment]
I've added a new section on key rotation, https://swicg.github.io/activitypub-http-signature/#key-rotation , and a new step in for handling it at the end of https://swicg.github.io/activitypub-http-signature/#how-to-verify-a-signature . Thanks for the nudges, all!
