### ISSUE TITLE
Note on why you throw away the key if it's fetched directly

### ISSUE THREAD

**Issue by evanp** [swicg/activitypub-http-signature#42]
It's probably worth mentioning why, if the `keyId` returns a `Key` object, you need to follow the `owner` property and fetch that instead. (The reason is to verify that the `owner` claims the key, and not just that the key claims the owner.)

**Comment by snarfed** [comment]
Yes! Agreed, will do.

**Comment by snarfed** [comment]
Tentatively closing. Feel free to re-open!
