### ISSUE TITLE
Distinction between GET and POST requests

### ISSUE THREAD

**Issue by evanp** [swicg/activitypub-http-signature#44]
Section 2.1 describes how to implement HTTP Signature for a POST request (notably, generating a Digest for the body). This isn't necessary or even possible for a GET request. Since signed GET requests are needed for Authorized Fetch, it'd be good to include this in the procedure, too.

**Comment by evanp** [comment]
I guess similarly for section 2.2. No need to hash the body.

**Comment by snarfed** [comment]
Hmm! I didn't mean for that section to be POST-specific. My experience (and code) expects and sends `Digest` headers for GETs as well as POSTs; GETs just have an empty request body.

I don't know how many existing fediverse servers require `Digest` for GETs in practice. @nightpool @perillamint @aumetra any idea?

**Comment by aumetra** [comment]
In general `Digest` doesn't make sense for GET requests, since the digest is always about the request body and a GET request just doesn't have a request body.  
So requiring one would always force the client to always send the same header

```
Digest: SHA-256=47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU=
```

The hash of an empty string/null. So I don't think any fediverse server requires the `Digest` header in practice for GET requests.

**Comment by snarfed** [comment]
Thanks @nightpool!

@aumetra you're definitely right that it doesn't make sense, but code in the wild often does all sorts of things that don't necessarily make sense. 😁 Eg my own code in Bridgy Fed [currently requires `Digest` on GET requests](https://github.com/snarfed/bridgy-fed/blob/933f21ce1e03852fb4ed02454eabc306d1af7643/activitypub.py#L453-L455), even though it probably shouldn't. One common reason may be that most servers will use the same code path for verifying POST and GET signatures.

Anyway, I was curious to hear other examples in the wild. Mastodon's is useful!

**Comment by perillamint** [comment]
Misskey version after 2023.11.1-beta.1
Firefish version after 1.0.5-rc
CherryPick version after 4.5.1

will require Digest header on `POST /inbox` 

Also, AFAIK, as of now, Misskey and its forks does not support signed GET on their resources (so, if someone misses mentioned people only message in their inbox, it is impossible to fetch it, even the valid recipient knows the status URL)

**Comment by snarfed** [comment]
Thanks all. Added language to section 2.1 that `Digest` may sometimes/usually be optional for GETs. Tentatively closing. Feel free to re-open!
