### ISSUE TITLE
No authorization check on authorized fetch

### ISSUE THREAD

**Issue by evanp** [swicg/activitypub-http-signature#46]
So, if I make a GET request for a `Note` that was posted "followers-only", the server will return the content just as long as my server isn't blocked? Addressee-only notes, or other "private" content?

That is a catastrophically bad privacy violation. I really hope this is not true. I'm going to be testing this out today to make sure.

**Comment by evanp** [comment]
OK, I don't think this is actually true. I just tried it with a private note on Mastodon, and a public note on Mastodon, and a followers-only post on Mastodon, and they all behaved as expected (got the content if my user should have access, 404 if not). I'm not crazy about the 404, but otherwise whatever.

I think you should update this part of the section on Authorized Fetch.

**Comment by nightpool** [comment]
Yeah, I think the intent with the spec here is to specify no *further
*fine-grained
access control is generally performed, although honestly I don't know if
that is true either. I think probably if you global suspend a user it'll
still get marked as a 401 response even if the entire instance isn't
blocked.

**Comment by snarfed** [comment]
Good to hear.

This feels like it's on the authorization side of the authn/authz divide, so I'm not sure that it's in scope for this report specifically, but I'm open to other opinions.

**Comment by nightpool** [comment]
I would just use very general language like "servers MAY place additional
implementation-specific restrictions on which actors are allowed to access
content"

**Comment by snarfed** [comment]
Thanks all! I've added this language to the authorized fetch section:

> For non-public data, eg followers-only or mention-only posts aka direct messages, servers generally do check that GET requests are signed by actors who should have access to that data.

Tentatively closing. Feel free to reopen!
