### ISSUE TITLE
Note on caching

### ISSUE THREAD

**Issue by evanp** [swicg/activitypub-http-signature#47]
It's probably worth mentioning that two GET requests even with the same key will have different `Signature` headers, because of the `Date` header.

I'd compare this with OAuth 2.0 with bearer tokens, in which multiple requests for the same user will have the same bearer token (until the token expires), so the `Authorization` header stays the same.

**Comment by snarfed** [comment]
Yes! https://swicg.github.io/activitypub-http-signature/#compatibility-with-http-caching currently includes this language:

> HTTP Signatures include timestamps, and are generated by different private keys, so they'll almost never be the same across requests.

Lmk if you think it needs more.

**Comment by evanp** [comment]
Yeah, it's the part that says "HTTP Signatures ... are generated by different private keys". Two GET requests for the same resource with the same private key will have different signatures because of the `Date` header being signed. If you feel like that's already covered and I'm just misreading it, I'm OK with that, too.

**Comment by snarfed** [comment]
True! I'll revise "are generated by different private keys," and I'll mention the `Date` header.

**Comment by snarfed** [comment]
Tentatively closing. Feel free to reopen!
