### ISSUE TITLE
Identify the Digest header algorithm

### ISSUE THREAD

**Issue by evanp** [swicg/activitypub-http-signature#5]
I've only seen SHA-256 supported.

**Comment by aumetra** [comment]
Pleroma and its forks hardcode SHA-256 as a requirement (so does Mastodon).  
Pleroma goes a step further though by literally replacing the digest header, so implementations that offer multiple choices in digests inside the digest header will break.

[Reference](https://git.pleroma.social/pleroma/pleroma/-/blob/991807080bfb35caf32f2403d61dd6ced66a9a50/lib/pleroma/web/plugs/digest_plug.ex)

**Comment by snarfed** [comment]
Incorporating into #33.
