### ISSUE TITLE
Describe how to transform a key id into an actor id

### ISSUE THREAD

**Issue by evanp** [swicg/activitypub-http-signature#9]
I think the algorithm is roughly:

If the key ID has a fragment...

- fetch the resource at the HTTPS URL
- look for a property with the same name as the fragment
- get the `owner` of that property

If the key ID does not have a fragment...

- fetch the resource at the HTTPS URL
- get the `owner` of that resource

**Comment by perillamint** [comment]
Also, I think the following constraints would be necessary:

- `publicKey[id]` MUST be a valid URI
- `publicKey[id]` MUST have the same authority as actor `id`  (To enforce server ban much more effectively)
- Validator MUST reject if an actor's `publicKey[id]` does not meet the criteria.

**Comment by evanp** [comment]
> For the `keyid` without fragment... I think it should (or must) be discouraged, because it will prevent us having multiple key slot in the future.

I don't think that's true at all. `https://social.example/key/1` and `https://social.example/key/2` can have the same owner property.

Also, `publicKey` can have multiple values.

**Comment by snarfed** [comment]
> Also, `publicKey` can have multiple values.

@evanp `publicKey` is https://w3c-ccg.github.io/security-vocab/#publicKey , right? Can you describe briefly how to confirm that it can be multiply valued? I'd like to incorporate that into https://github.com/swicg/activitypub-http-signature/issues/8#issuecomment-2026362974.

**Comment by tesaguri** [comment]
> > Also, `publicKey` can have multiple values.
> 
> `publicKey` is https://w3c-ccg.github.io/security-vocab/#publicKey , right? Can you describe briefly how to confirm that it can be multiply valued?

The property isn't defined to be "functional" (single-valued), and generally speaking, an RDF property not explicitly specified to be functional can have multiple values because the functionality is opt-in IIUC.

And that seems to actually match the intention of the Security Vocabulary spec, since the spec has a number of examples that use the term with an array value (search for `"publicKey": [` in the spec!).

**Comment by snarfed** [comment]
Thanks @tesaguri!
